### ISSUE TITLE
可以弄一个docker镜像吗，感觉会省事很多。

### ISSUE THREAD

**Issue by zh0ub0** [c0ny1/upload-labs#10]

**Comment by c0ny1** [comment]
部分Pass需要Windows特性才能上传成功，故最好搭建在Windows上。项目已经为大家提供了一个集成环境，在releases中。

**Comment by rudrasingh99** [comment]
please make english version.

**Comment by c0ny1** [comment]
@rudrasingh99 Sorry, my English is poor. I'll try later. Or some Internet Security enthusiasts are willing to translate the project.

**Comment by the-c0d3r** [comment]
@c0ny1 I'm willing to translate the project. Can you tell me how to do that, maybe fork the project and translate all the Chinese strings, then create a Pull Request?

**Comment by c0ny1** [comment]
@the-c0d3r 很抱歉没有注意到你的信息！对于国际化，我暂时还没有更好的方案。我觉得你可以先fork项目,暂时不用pull requests。等有不错的方案去实现多语言时，我会参考的翻译成果。你觉得如何？
