### ISSUE TITLE
Docker启动项目没有upload目录

### ISSUE THREAD

**Issue by pench3r** [c0ny1/upload-labs#12]
但是在docker中无法直接创建提示没有mkdir命令，建议在项目中直接添加一个空的upload目录。

**Comment by c0ny1** [comment]
点击“清空上传文件”按钮，即可生成upload目录。github无法上传空目录。近期会调整代码自动创建该目录。

**Comment by pench3r** [comment]
嗯嗯 谢谢回复，我自己是修改了一下Dockerfile文件直接创建目录了。
