### ISSUE TITLE
windows集成环境中phpstudy无法启动MySQL

### ISSUE THREAD

**Issue by erfze** [c0ny1/upload-labs#13]
我在windows7下搭建环境时发现phpstudy的MySQL服务无法启动，从网上也没有找到合适的解决方案，然后到[http://www.php.cn/xiazai/gongju/714](url)下载了phpstudy2018，再切换版本，并将WWW目录下的文件复制过去就正常启动了。遇到同样问题的朋友可通过erfze1999@163.com联系我。

**Comment by c0ny1** [comment]
upload-labs不需要数据库，为了减少集成环境的大小，所以在制作时将Mysql删除掉了。无法启动是正常的。

**Comment by erfze** [comment]
是这样，谢谢答复，受教了
