### ISSUE TITLE
关于pass3的题解

### ISSUE THREAD

**Issue by Y4er** [c0ny1/upload-labs#14]
最新版将上传的文件重命名，无法通过.htaccess、apache解析漏洞、`.空格`绕过，请教题解。

另外希望出系统的writeup，网上的不是很全。

**Comment by c0ny1** [comment]
1. Pass-03是黑名单的第一个Pass，比较简单，可以看看提示和代码。同时注意该Pass依赖apache配置，推荐使用[realses](https://github.com/c0ny1/upload-labs/releases)中已经配置好的集成环境。
2. 为了靶场的发展和防止学习者固定思维，靶场不单独出writeup，希望大家能多交流发现更多的绕过方式，靶场也会跟进大家交流的成果，做一个更全面的总结。

**Comment by zero-llx** [comment]
> 1. Pass-03是黑名单的第一个Pass，比较简单，可以看看提示和代码。同时注意该Pass依赖apache配置，推荐使用[realses](https://github.com/c0ny1/upload-labs/releases)中已经配置好的集成环境。
> 2. 为了靶场的发展和防止学习者固定思维，靶场不单独出writeup，希望大家能多交流发现更多的绕过方式，靶场也会跟进大家交流的成果，做一个更全面的总结。

请问我可以理解为 pass3中出现文件重命名情况，是由于环境版本导致的吗？

**Comment by c0ny1** [comment]
是后续版本为了解决本issuse所说的问题

**Comment by c0ny1** [comment]
@zero-llx 本issue已经关闭，有问题重新开issuse。
