### ISSUE TITLE
pass 16上传路径出错

### ISSUE THREAD

**Issue by tgllsy** [c0ny1/upload-labs#19]
docker 的pass16 文件上传后会把路径`upload`包含在文件名内，在网站根目录生成`upload图片名.jpg`文件。

**Comment by cn9eek** [comment]
在pass-18里面发生了类似的情况，发现index.php中如下代码：
`$status_code = $u->upload(UPLOAD_PATH);`
少一个/ 
修改为：
`$status_code = $u->upload(UPLOAD_PATH.'/');`

不知道作者怎么看呢？
