### ISSUE TITLE
Docker中php版本太高，导致无法利用00截断和Windows特性

### ISSUE THREAD

**Issue by sharp-shooter** [c0ny1/upload-labs#20]
docker里边版本太高了吧  截断漏洞不能利用 利用Windows特性的漏洞也不能利用

**Comment by c0ny1** [comment]
1. docker版本主要是为了为Pass-19解决环境问题的，只能尽可能的兼容其他Pass。
2. docker只有Linux镜像，故涉及Windows特性的Pass，无法突破。

以上在项目文档已有说明，建议除了`Pass-19`使用docker环境，其他使用项目打包好的[集成环境](https://github.com/c0ny1/upload-labs/releases)，在Windows下运行。

**Comment by sharp-shooter** [comment]
Pass-19在Windows下利用1.php.        这种方式也能绕过吧

**Comment by c0ny1** [comment]
Pass-19考察了漏洞是在Linux下，而不是Windows。代码在Windows下有多种方式绕过，与其他Pass漏洞重复了，没有意义。

**Comment by sharp-shooter** [comment]
docker怎么把php的版本改成php5.2 我一直没成功呢

**Comment by c0ny1** [comment]
请贴下报错信息
