### ISSUE TITLE
Pass-04 显示源码和源文件index.php上传路径不同

### ISSUE THREAD

**Issue by groaptx** [c0ny1/upload-labs#22]
页面提示源码：$img_path = UPLOAD_PATH.'/'.date("YmdHis").rand(1000,9999).$file_ext;
源文件： $img_path = UPLOAD_PATH.'/'.$file_name;

**Comment by c0ny1** [comment]
最新源码`$img_path`是一致的，release没有更新到最新源码，可能是这个原因。
