### ISSUE TITLE
上传操作抓不到数据包

### ISSUE THREAD

**Issue by xiaoduwu** [c0ny1/upload-labs#24]
您好~我利用您提供的“upload-labs-env-win-0.1-beat.1”在win7系统上运行，上传的数据包用burp抓不到，但是“清空上传文件”和“查看提示”的数据包能抓，请问，会是什么情况造成的呀？
只能抓到这两个链接：
http://127.0.0.1/Pass-01/helper.php?action=get_prompt
http://127.0.0.1/rmdir.php?action=clean_upload_file

打扰您了~~

**Comment by zero-llx** [comment]
> 您好~我利用您提供的“upload-labs-env-win-0.1-beat.1”在win7系统上运行，上传的数据包用burp抓不到，但是“清空上传文件”和“查看提示”的数据包能抓，请问，会是什么情况造成的呀？
> 只能抓到这两个链接：
> http://127.0.0.1/Pass-01/helper.php?action=get_prompt
> http://127.0.0.1/rmdir.php?action=clean_upload_file
> 
> 打扰您了~~

请问您后来找到原因和解决办法了吗？我也遇到了同样的问题。
