### ISSUE TITLE
可不可以出一个官方的攻略啊？

### ISSUE THREAD

**Issue by CatAndCoffee** [c0ny1/upload-labs#29]
从Pass-03开始就磕磕绊绊的了……网上的攻略千篇一律，但是都不能用，不知道是不是我操作的问题，还是环境出问题了:worried:。docker中没找到vi、nano、vim等编辑工具，apache2.conf都没法修改

**Comment by c0ny1** [comment]
1. 项目不会出writeup，期待能各位能发现同一个Pass出现多种方法突破，项目会跟进跟新。
2. 关于环境，为了减少时间建议使用[项目打包好的环境](https://github.com/c0ny1/upload-labs/releases)在Windows下搭建。除了Pass19需要Linux环境（docker），其余Pass均可以在Windows下复现成功。

**Comment by No-Github** [comment]
> 
> 
> 从Pass-03开始就磕磕绊绊的了……网上的攻略千篇一律，但是都不能用，不知道是不是我操作的问题，还是环境出问题了😟。docker中没找到vi、nano、vim等编辑工具，apache2.conf都没法修改

之前有对网上攻略做个总结，你可以看一下😆
https://github.com/No-Github/1earn/blob/master/1earn/%E5%AE%89%E5%85%A8/%E5%AE%9E%E9%AA%8C/upload-labs%E5%B0%8F%E8%AE%B0.md

**Comment by yyanyi213** [comment]
> 从Pass-03开始就磕磕绊绊的了……网上的攻略千篇一律，但是都不能用，不知道是不是我操作的问题，还是环境出问题了😟。docker中没找到vi、nano、vim等编辑工具，apache2.conf都没法修改

目前docker搭载的php版本是5.5.38，我的pass4 5也是很有问题，弄不出来。win的集成环境没问题

**Comment by c0ny1** [comment]
@yyanyi213 docker版本主要针对Pass19进行搭建。说白了就是Pass1-18和Pass20最好在win下运行，Pass19必须在Linux下运行。

**Comment by yyanyi213** [comment]
嗯嗯，项目确实蛮好的，感谢您。
