### ISSUE TITLE
Docker may be better！

### ISSUE THREAD

**Issue by MasonQAQ** [c0ny1/upload-labs#3]
RT

**Comment by 296537044** [comment]
Agree

**Comment by c0ny1** [comment]
@MasonQAQ 该靶场部分Pass需要利用windows文件系统的特性，所以不好做docker镜像。

**Comment by MasonQAQ** [comment]
@c0ny1 那是否可以详细说明下环境搭建教程，我之前一般使用xampp这样的集成包，是不是不行？

**Comment by c0ny1** [comment]
@MasonQAQ 可以，不过还是推荐使用phpstudy，这样方便切换版本。保证以下三点即可运行所有Pass。
1.php版本：推荐5.2.17
2.apache是以module方式连接php
3.Pass-01到Pass-18都可以在windows下，Pass-19只能在linux下。
