### ISSUE TITLE
Windows集成环境绿色免安装版本的pass13

### ISSUE THREAD

**Issue by klmyssn** [c0ny1/upload-labs#34]
在做这一关的时候上传完图片木马想找个包含漏洞利用发现也没给提示，网上找的wp发现这一关是有给文件包含漏洞地址的，但是我这个怎么没有，是这个集成环境版本把这个删除了吗，我也没发现根目录有include文件……
![图片](https://user-images.githubusercontent.com/37890522/75598408-690a3800-5ad6-11ea-8cd9-ba275253153f.png)

**Comment by c0ny1** [comment]
集成环境不是最新靶场源码，可以自行把代码更新下。

**Comment by klmyssn** [comment]
好的。清楚了。感谢。
