### ISSUE TITLE
能否提供所有example的wp

### ISSUE THREAD

**Issue by MasonQAQ** [c0ny1/upload-labs#4]
能否提供下每个题简单的解题思路，有的案例是不是要求对apache进行配置？比如lab3，我能想到上传htaccess和php5等方法，但是好像都不管用。

**Comment by c0ny1** [comment]
@MasonQAQ 思路方面每个Pass都有提示和代码，同时思维导图已经提示得很明显了。其次你说的环境问题我也注意到了，所以在realse上传了一个符合项目运行的php集成环境，可一键运行配置好的环境，看看能不能帮助到你。

**Comment by jishuzhain** [comment]
pass6是不是代码有问题，没有找到deldot()，而pass6中的php代码没有包含common.php。

**Comment by c0ny1** [comment]
@jishuzhain 是的，不过最新代码已经解决了这个bug。
