### ISSUE TITLE
Pass-19 suggestion

### ISSUE THREAD

**Issue by LandGrey** [c0ny1/upload-labs#5]
I always forget to fill in file "save_name" value and submit forms，it will cause warning 
```
Warning: move_uploaded_file(../upload//) [function.move-uploaded-file]: failed to open stream: Permission denied in /web/path/to/upload-labs/Pass-19/index.php on line 18
Warning: move_uploaded_file() [function.move-uploaded-file]: Unable to move 'C:\Users\Username\AppData\Local\Temp\xxxxx.tmp' to '../upload//' in /web/path/to/upload-labs/Pass-19/index.php on line 18
```
and upload failed. so, I suggested add default value for "save_name" and modify the [Pass-19](https://github.com/c0ny1/upload-labs/blob/master/Pass-19/index.php) source code line 45, code example
 ` <input class="input_text" type="text" name="save_name" value="upload_19.jpg" style="" /><br/>`

**Comment by c0ny1** [comment]
That's a good idea, and I've updated the code.
