### ISSUE TITLE
Pass-04上传.htaccess无法解析jpg

### ISSUE THREAD

**Issue by LIVVM** [c0ny1/upload-labs#51]
你好，我是个初学者。我在学习第4关的时候，学习了利用.htaccess文件进行绕过。但是我使用phpstudy搭建的靶场在上传了.htaccess之后上传木马jpg再使用蚁剑却无法链接。参考了别人的博客说要改Apache的httpd.conf的配置，我改了好像无济于事。请问这是为什么？

**Comment by 2367611731** [comment]
建议使用哥斯拉或者冰蝎进行连接，可以使用这些工具内置shell。



***@***.***
 
发件人： LiVVM
发送时间： 2022-05-08 22:21
收件人： c0ny1/upload-labs
抄送： Subscribed
主题： [c0ny1/upload-labs] Pass-04上传.htaccess无法解析jpg (Issue #51)
你好，我是个初学者。我在学习第4关的时候，学习了利用.htaccess文件进行绕过。但是我使用phpstudy搭建的靶场在上传了.htaccess之后上传木马jpg再使用蚁剑却无法链接。参考了别人的博客说要改Apache的httpd.conf的配置，我改了好像无济于事。请问这是为什么？

**Comment by LIVVM** [comment]
好像这样的结果是一样的

**Comment by LIVVM** [comment]
好像用冰蝎去链接还是链接不上，我不会用冰蝎的其他功能，只是像使用蚁剑一样使用冰蝎

**Comment by Z3ratu1** [comment]
先验证一下马能不能运行。如果马根本不能运行的话很有可能是因为你用的是nts版本的php，nts下setHandler那堆操作不能直接用
