### ISSUE TITLE
提个小建议。

### ISSUE THREAD

**Issue by NAXG** [c0ny1/upload-labs#8]
建议写上每个任务写上让用什么方法来绕过。
当我发现xxx.php.xxx可以绕过所有题目时，就索然无味了

**Comment by Yangzcc** [comment]
黑名单可以再添加一个pht后缀.

**Comment by hellopentest** [comment]
> 建议写上每个任务写上让用什么方法来绕过。
> 当我发现xxx.php.xxx可以绕过所有题目时，就索然无味了

上传后又不能执行，不算绕过

**Comment by c0ny1** [comment]
已经通过重命名方式，解决了大部分Pass存在的该问题。

**Comment by c0ny1** [comment]
https://github.com/c0ny1/upload-labs/commit/363a94f81c68ac6f5326bbb0303dccaed3391c61
